name = "MagicFormulaTyre"
uuid = "1965a319-4641-4c31-815f-5ff176c30ddb"
authors = ["Ahmed Mogahed <a.mogahed@inginne.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
